-- Tag catalog for manual tagging demo (wine, brewery, logistics)
CREATE TABLE public.tag_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX tag_catalog_name_lower_idx ON public.tag_catalog (lower(name));

ALTER TABLE public.tag_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read tag catalog"
  ON public.tag_catalog FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert tag catalog"
  ON public.tag_catalog FOR INSERT TO authenticated WITH CHECK (true);

INSERT INTO public.tag_catalog (name)
SELECT v FROM unnest(ARRAY[
  'Cabernet Sauvignon',
  'Merlot',
  'Pinot Noir',
  'Syrah',
  'Shiraz',
  'Grenache',
  'Mourvèdre',
  'Malbec',
  'Petit Verdot',
  'Cabernet Franc',
  'Sangiovese',
  'Nebbiolo',
  'Barbera',
  'Dolcetto',
  'Montepulciano',
  'Primitivo',
  'Aglianico',
  'Tempranillo',
  'Garnacha',
  'Monastrell',
  'Pinot Grigio',
  'Pinot Gris',
  'Chardonnay',
  'Sauvignon Blanc',
  'Riesling',
  'Gewürztraminer',
  'Viognier',
  'Chenin Blanc',
  'Semillon',
  'Muscadet',
  'Albariño',
  'Verdejo',
  'Grüner Veltliner',
  'Chablis',
  'Sancerre',
  'Pouilly-Fumé',
  'Vinho Verde',
  'Port Wine',
  'Sherry',
  'Madeira',
  'Vermouth',
  'Prosecco',
  'Cava',
  'Champagne',
  'Crémant',
  'Lambrusco',
  'Zinfandel',
  'Petite Sirah',
  'Carignan',
  'Cinsault',
  'Counoise',
  'Tannat',
  'Touriga Nacional',
  'Assyrtiko',
  'Xinomavro',
  'Pinot Blanc',
  'Pinot Meunier',
  'Marsanne',
  'Roussanne',
  'Clairette',
  'Picpoul',
  'Fiano',
  'Greco di Tufo',
  'Vermentino',
  'Trebbiano',
  'Gamay',
  'Pinotage',
  'St. Laurent',
  'Blaufränkisch',
  'Zweigelt',
  'Furmint',
  'Hárslevelű',
  'Kadarka',
  'Mavrud',
  'Carménère',
  'País',
  'Torrontés',
  'Bonarda',
  'Trousseau',
  'Ploussard',
  'Savagnin',
  'Jacquère',
  'Romorantin',
  'Encruzado',
  'Bical',
  'Arinto',
  'Loureiro',
  'Mencía',
  'Graciano',
  'Bobal',
  'Napa Valley',
  'Sonoma County',
  'Russian River Valley',
  'Carneros AVA',
  'Dry Creek Valley',
  'Alexander Valley',
  'Paso Robles',
  'Santa Barbara County',
  'Santa Ynez Valley',
  'Willamette Valley',
  'Columbia Valley AVA',
  'Walla Walla Valley',
  'Horse Heaven Hills',
  'Red Mountain AVA',
  'Finger Lakes',
  'Long Island Wine Country',
  'Virginia Monticello AVA',
  'Texas High Plains',
  'Georgia Wine Trail',
  'Bordeaux Left Bank',
  'Bordeaux Right Bank',
  'Burgundy Côte d Or',
  'Champagne Montagne de Reims',
  'Alsace Wine Route',
  'Loire Anjou',
  'Loire Touraine',
  'Rhône Northern',
  'Rhône Southern',
  'Provence Rosé Coast',
  'Languedoc Pic Saint-Loup',
  'Roussillon Banyuls',
  'South West Jurançon',
  'Jura Wine Region',
  'Savoie Wine',
  'Beaujolais Crus',
  'Corsica Patrimonio',
  'Piedmont Barolo',
  'Piedmont Barbaresco',
  'Tuscany Chianti Classico',
  'Tuscany Brunello',
  'Veneto Valpolicella',
  'Veneto Soave',
  'Lombardy Franciacorta',
  'Sicily Etna',
  'Puglia Primitivo Land',
  'Campania Taurasi',
  'Alto Adige Südtirol',
  'Friuli Colli Orientali',
  'Emilia Lambrusco Land',
  'Rioja Alta',
  'Rioja Alavesa',
  'Ribera del Duero',
  'Priorat DOQ',
  'Rías Baixas Albariño',
  'Jerez Sherry Triangle',
  'La Mancha',
  'Toro DO',
  'Bierzo Mencía',
  'Rueda Verdejo',
  'Douro Valley Port',
  'Alentejo Wine',
  'Dão Wine Region',
  'Vinho Verde Minho',
  'Madeira Wine',
  'Mosel Steep Slopes',
  'Rheingau Riesling',
  'Pfalz Germany',
  'Baden Pinot',
  'Franken Silvaner',
  'Wachau Smaragd',
  'Burgenland Blaufränkisch',
  'Styria Sauvignon',
  'Tokaj Aszú',
  'Eger Bikavér',
  'Villány Reds',
  'Stellenbosch Wine',
  'Paarl Valley',
  'Franschhoek Valley',
  'Swartland Revolution',
  'Walker Bay Pinot',
  'Hunter Valley Semillon',
  'Barossa Shiraz',
  'McLaren Vale Grenache',
  'Adelaide Hills Chardonnay',
  'Yarra Valley Pinot',
  'Margaret River Cabernet',
  'Tasmania Sparkling',
  'Marlborough Sauvignon',
  'Central Otago Pinot',
  'Hawkes Bay Bordeaux Blend',
  'Wairarapa Pinot',
  'Casablanca Chile',
  'Colchagua Carmenère',
  'Maipo Cabernet',
  'Curicó Valley',
  'Mendoza Malbec',
  'Salta Torrontés High',
  'Patagonia Pinot',
  'Uruguay Tannat Coast',
  'Bekaa Valley Lebanon',
  'Golan Heights Wine',
  'Santorini Assyrtiko',
  'Crete Vilana',
  'Kakheti Saperavi',
  'Armenia Areni',
  'English Sparkling Wine',
  'Anderson Valley Pinot',
  'Santa Cruz Mountains Cabernet',
  'Santa Lucia Highlands Pinot',
  'Edna Valley Chardonnay',
  'Arroyo Grande Valley',
  'Lodi Old Vine',
  'Clarksburg Chenin',
  'Lake County Sauvignon',
  'Mendocino Ridge Zin',
  'Yorkville Highlands',
  'Wahluke Slope',
  'Snipes Mountain',
  'Rattlesnake Hills',
  'Columbia Gorge AVA',
  'Umpqua Valley',
  'Rogue Valley',
  'Applegate Valley',
  'Snake River Valley Idaho',
  'Lehigh Valley PA',
  'Lake Erie NY',
  'Seneca Lake NY',
  'Cayuga Lake NY',
  'Hudson River Region',
  'Middleburg Virginia',
  'Monticello Virginia AVA',
  'Bell Mountain Texas',
  'Escondido Valley Texas',
  'Pecos County Texas',
  'Ohio River Valley Winery',
  'Missouri Augusta AVA',
  'Arkansas Wine Country',
  'Oklahoma Winery Region',
  'New Mexico Wine Trail',
  'Colorado Grand Valley',
  'Utah Wine',
  'Arizona Verde Valley',
  'Nevada Winery Region',
  'Harvest Season',
  'Crush Pad',
  'Primary Fermentation',
  'Malolactic Conversion',
  'Barrel Program',
  'French Oak Barrels',
  'American Oak Barrels',
  'Neutral Barrels',
  'Brix Testing',
  'Acidity Management',
  'Sulfur Management',
  'Racking Wine',
  'Fining Agents',
  'Cross Flow Wine Filter',
  'Bottling Run',
  'Label Compliance',
  'Case Packing',
  'DTC Allocation',
  'Wine Club Shipments',
  'Wholesale Portfolio',
  'On-Premise Accounts',
  'Off-Premise Retail',
  'Tasting Room Host',
  'Cellar Rat',
  'Winemaking Assistant',
  'Vineyard Crew',
  'Viticulture Team',
  'Canopy Work',
  'Veraison Monitoring',
  'Terroir Expression',
  'Clonal Material',
  'AVA Labeling',
  'Estate Grown',
  'Single Vineyard Designate',
  'Whole Cluster Press',
  'Carbonic Maceration',
  'Extended Maceration',
  'Sur Lie Aging',
  'Lees Work',
  'Biodynamic Certification',
  'Organic Grapes',
  'Sustainable WA',
  'Dry Farming',
  'Old Vine Zinfandel',
  'Natural Wine Movement',
  'Orange Wine Style',
  'Pet-Nat Sparkling',
  'Solera Aging',
  'Fortified Production',
  'Ice Wine Harvest',
  'American IPA',
  'West Coast IPA',
  'Hazy IPA',
  'New England IPA',
  'Double IPA',
  'Triple IPA',
  'Session IPA',
  'English IPA',
  'Belgian IPA',
  'Black IPA',
  'American Pale Ale',
  'Best Bitter',
  'Extra Special Bitter',
  'Blonde Ale',
  'Golden Ale',
  'Kölsch Service',
  'Cream Ale',
  'Steam Beer',
  'Amber Ale',
  'Irish Red Ale',
  'Brown Porter',
  'Robust Porter',
  'Baltic Porter',
  'Dry Irish Stout',
  'Sweet Stout',
  'Oatmeal Stout',
  'Foreign Extra Stout',
  'American Stout',
  'Imperial Stout',
  'Barrel-Aged Imperial',
  'American Adjunct Lager',
  'International Pale Lager',
  'German Pilsner',
  'Bohemian Pilsner',
  'Munich Helles',
  'Festbier',
  'Märzen Lager',
  'Vienna Lager',
  'Munich Dunkel',
  'Schwarzbier',
  'Traditional Bock',
  'Maibock',
  'Doppelbock',
  'Eisbock',
  'Weissbier',
  'Dunkelweizen',
  'Weizenbock',
  'Belgian Wit',
  'Saison Farmhouse',
  'Bière de Garde',
  'Belgian Dubbel',
  'Belgian Tripel',
  'Belgian Dark Strong',
  'Oud Bruin',
  'Flanders Red',
  'Lambic Tradition',
  'Gueuze Blend',
  'Fruit Lambic',
  'Berliner Weisse',
  'Contemporary Gose',
  'English Barleywine',
  'American Barleywine',
  'Wee Heavy',
  'Rye IPA',
  'Honey Beer',
  'Rauchbier',
  'Grodziskie',
  'Kentucky Common',
  'Czech Dark Lager',
  'Italian Pilsner',
  'Cold IPA',
  'Brut IPA',
  'Japanese Rice Lager',
  'Mexican Amber Lager',
  'Pastry Stout',
  'Smoothie Sour',
  'Slushy Beer',
  'Brett IPA',
  'Wild Ale Blend',
  'Mixed Culture Beer',
  'Brewhouse Operations',
  'Mash Conversion',
  'Lautering',
  'Wort Boil',
  'Whirlpool Rest',
  'Wort Cooling',
  'Fermenter CIP',
  'Ale Fermentation',
  'Lager Fermentation',
  'Diacetyl Rest',
  'Dry Hop Charge',
  'Centrifuge Clarification',
  'Beer Filtration',
  'Bright Tank Carbonation',
  'Can Depalletizer',
  'Filler Seamer',
  'Pasteurization Tunnel',
  'Keg Cleaning',
  'Keg Filling',
  'Quality Assurance Lab',
  'Sensory Evaluation',
  'Yeast Brink',
  'Yeast Propagation',
  'Grain Handling',
  'Grist Ratio',
  'Hop Storage Cold',
  'Brewpub Service',
  'Taproom Manager',
  'Pilot Batch',
  'Recipe Scaling',
  'Craft Distribution',
  'Self-Distribution',
  'Cold Storage Beer',
  'Hop Contracts',
  'Malt Silo Fill',
  'Adjunct Sugar',
  'High Gravity Brewing',
  'Low Oxygen Brewing',
  'Dissolved Oxygen Control',
  'Packaging Date Code',
  'Citra Hops',
  'Mosaic Hops',
  'Simcoe Hops',
  'Amarillo Hops',
  'Centennial Hops',
  'Cascade Hops',
  'Galaxy Hops',
  'Nelson Sauvin Hops',
  'Motueka Hops',
  'Sabro Hops',
  'Cashmere Hops',
  'Strata Hops',
  'El Dorado Hops',
  'Azacca Hops',
  'Loral Hops',
  'Hallertau Mittelfrüh',
  'Saaz Hops',
  'Fuggle Hops',
  'East Kent Goldings',
  'Cryo Hop Pellets',
  'Phantasm Thiol Powder',
  'Cocoa Nibs Beer',
  'Vanilla Bean Stout',
  'Coffee Porter',
  'Maple Barrel Beer',
  'Coconut Porter',
  'Lactose IPA',
  'Brettanomyces Blend',
  'Lactobacillus Kettle Sour',
  'Pediococcus Barrel',
  'Foeder Program',
  'Coolship Inoculation',
  'Spontaneous Coolship',
  'Brett IPA House',
  'Kettle Sour Quick',
  'Pastry Sour Series',
  'Italian Pils Program',
  'Czech Lager Decoction',
  'Roggenbier Rye',
  'Lichtenhainer Smoked Sour',
  'Case Stacker Warehouse',
  'Pallet Inverter Line',
  'Stretch Wrap Machine',
  'Shrink Bundler',
  'Depalletizer Infeed',
  'Bottle Filler Wine',
  'Corking Line',
  'Screwcap Applicator',
  'Labeler Cold Glue',
  'X-Ray Fill Level',
  'Glass Bottle QC',
  'PET Bottle Line',
  'Bag in Box Filler',
  'Keg Cleaning System',
  'Cooperage Inspection',
  'Reconditioned Whiskey Barrel',
  'Stainless Tank Farm',
  'Pump Over Schedule',
  'Punch Down Crew',
  'Cap Management Punch',
  'Cold Soak Protocol',
  'Thermovinification',
  'Flash Detente Extraction',
  'Plate Frame Filter',
  'RO Wine Concentrate',
  'Fortified Liqueur Blending',
  'Solera Row Management',
  'Sparkling Tirage',
  'Disgorging Line',
  'Dosage Liqueur',
  'CDL-A',
  'CDL-B',
  'Class A Commercial Driver',
  'Class B Commercial Driver',
  'DOT Medical Card',
  'Hours of Service Rules',
  'ELD Electronic Logging',
  'Tanker Endorsement',
  'Hazmat Endorsement',
  'Doubles Triples Endorsement',
  'TWIC Credential',
  'Sit-Down Forklift',
  'Stand-Up Forklift',
  'Reach Truck Operator',
  'Order Picker Forklift',
  'Cherry Picker Lift',
  'Electric Pallet Jack',
  'Manual Pallet Jack',
  'Walkie Stacker',
  'Clamp Truck Forklift',
  'Double Deep Reach Truck',
  'Counterbalance Forklift',
  'Load Securement FMCSA',
  'Freight Handler',
  'Loading Dock Worker',
  'Yard Jockey Truck',
  'Spotter Truck'
]::text[]) AS t(v);

-- Additional forklift / warehouse driver tags (ensures 30+ logistics-specific labels)
INSERT INTO public.tag_catalog (name)
SELECT v
FROM unnest(ARRAY[
  'Warehouse Associate',
  'MHE Equipment Operator',
  'OSHA Forklift Certified',
  'PIT Powered Industrial Truck',
  'High Reach Forklift',
  'Very Narrow Aisle',
  'VNA Man-Up Truck',
  'Turret Truck Order',
  'Pallet Flow Rack',
  'Case Pick Voice',
  'Full Pallet Selector',
  'Cross-Dock Operation',
  'Dunnage Removal'
]::text[]) AS t(v)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tag_catalog tc WHERE lower(tc.name) = lower(t.v)
);
