-- Additional skill-focused tags: forklift operation (~30) and logistics / CDL / supply chain (~50).
-- Idempotent: skips rows that already exist (case-insensitive).

INSERT INTO public.tag_catalog (name)
SELECT v
FROM unnest(ARRAY[
  -- Forklift & powered industrial trucks (skills / certifications / operations)
  'Raymond Reach Truck Certified',
  'Crown Reach Truck Operator',
  'Toyota Lift Truck Operator',
  'Hyster Forklift Operation',
  'Propane Forklift Operation',
  'Electric Counterbalance Forklift',
  'Rough Terrain Forklift RTFL',
  'Telehandler Forklift Basics',
  'Side Loader Forklift Operation',
  'Swing-Reach Forklift Certified',
  'Double-Deep Reach Forklift',
  'Carton Clamp Forklift Operation',
  'Paper Roll Clamp Experience',
  'Slip Sheet Forklift Attachment',
  'Drum Handling Forklift',
  'Push Back Rack Forklift Picking',
  'Drive-In Rack Forklift Operation',
  'Straddle Stacker Operation',
  'Pallet Stacker Walkie Operation',
  'Powered Pallet Rider PPT',
  'Forklift Pre-Operational Inspection',
  'Forklift Load Chart & Stability',
  'Forklift Battery Change-Out Safety',
  'LPG Cylinder Exchange Safety',
  'Narrow Aisle Man-Up Order Picker',
  'High-Level Order Picker Certified',
  'Turret Truck Man-Up Operation',
  'RF Scanning While Forklift Picking',
  'Voice-Directed Forklift Picking',
  'Multi-Shift Forklift Operation',

  -- Logistics, CDL, freight, warehouse flow
  'CDL Class A Combination Vehicle',
  'CDL Class B Straight Truck',
  'CMV Pre-Trip DOT Inspection',
  'FMCSA Hours of Service Compliance',
  'ELD Electronic Logging Proficiency',
  'CDL Tanker Endorsement N',
  'CDL Hazmat Endorsement H',
  'CDL Doubles Triples Endorsement T',
  'CDL Passenger Endorsement P',
  'CDL School Bus Endorsement S',
  'Air Brake Restriction Removal',
  'DOT Clearinghouse Query Basics',
  'MCSA Medical Certificate Renewal',
  'ELDT Entry-Level Driver Training',
  'Straight Truck P&D Driver',
  'Box Truck Last-Mile Delivery',
  'Flatbed Load Securement FMCSA',
  'Reefer Trailer Temp Monitoring',
  'Dry Van Drop and Hook',
  'Yard Hostler Spotter Truck',
  'Warehouse Shuttle Driver',
  'OTR Linehaul Experience',
  'LTL P&D City Route',
  'Drayage Container Chassis',
  'Intermodal Ramp Operation',
  'Weigh Station & Scale House',
  'Bill of Lading BOL Accuracy',
  'Proof of Delivery POD Capture',
  'TMS Load Tender Basics',
  'Route Planning & ETA Updates',
  'Cross-Dock Sort & Segregate',
  'ASN Advanced Shipping Notice',
  'WMS Directed Picking',
  'Cycle Count & Inventory Accuracy',
  'Shipping Clerk Packing Station',
  'Receiving Clerk Unload Verification',
  'Dock Appointment Scheduling',
  'RMA Returns Dock Processing',
  'Parcel Manifest Auditing',
  'LTL Freight Class & NMFC',
  'Freight Claim Filing Basics',
  'Cold Chain GDP Awareness',
  'OTIF On-Time In-Full Metrics',
  '3PL Warehouse Coordination',
  'Import Export Documentation Basics',
  'Dangerous Goods IATA IMDG Aware',
  'FIFO FEFO Lot Picking',
  'Serialized SKU Handling',
  'Milk Run Inbound Scheduling',
  'Carrier Appointment Compliance'
]::text[]) AS t(v)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tag_catalog tc WHERE lower(tc.name) = lower(t.v)
);
